### PR TITLE
WIP: Better logging, reduce logspam & clean up docstrings

### PR DESCRIPTION
**Pull request by zxdavb**
Sorry Andrew, I am pushing changes faster than I like, because I want to get them in before 0.2.9 is tagged & pushed to PyPi!

This PR fixed a bug introduced with logging.  It also adds some logging to aid with debugging of refresh token failure. It reduces the number of these messages to one (only during instantiation):
```
DEBUG: __init__(): Debug mode was not explicitly enabled.
```

Docstrings that extend beyond 1 line should have the end-triple-quote on a line by themselves.

### CODE REVIEW

**Comment by zxdavb** [comment]
@watchforstock

In `__init__.py` there is:
```python
class EvohomeClient(EvohomeBase):                                                # pylint: disable=too-many-instance-attributes
    """Provides access to the Evohome API"""

    # pylint: disable=too-many-arguments
    def __init__(self, username, password, debug=False, refresh_token=None,
                 access_token=None, access_token_expires=None):
        super(EvohomeClient, self).__init__(debug)
```

But in the other modules (e.g. `controlsystem.py`), there is:
```python
class ControlSystem(EvohomeBase):
    """Provides handling of a control system"""

    def __init__(self, client, location, gateway, data=None):
        super(ControlSystem, self).__init__()
```

Is the second super supposed to include: `debug=False`?

**Comment by zxdavb** [comment]
Are you OK if I just refactor this whole thing? I think we can just dispose of `base.py`.

**Comment by watchforstock** [comment]
> Are you OK if I just refactor this whole thing? I think we can just dispose of `base.py`.

Yes I think so. If I remember back, I think I thought there'd be more "standard" processing that each object would need to do, but it turned out not to be true. As I was doing some of the clean up the other night I thought that it looked largely redundant.

**Comment by watchforstock** [comment]
> Sorry Andrew, I am pushing changes faster than I like, because I want to get them in before 0.2.9 is tagged & pushed to PyPi!

I wouldn't worry too much about "missing" a release. I'm trying to improve the process by automating the release process so it should be easier to do releases in the future. I'll comment in the other thread, but I'm inclined to get this branch onto master soon so we can track the different changes (linting, testing etc) separately

**Comment by zxdavb** [comment]
Yea go-on. I've introduced a regression & can't sort it out.

Also, think I found a bug that affects people with multiple locations - watch this space!

**Pull request closed without merging**
